### ISSUE TITLE
Good work!!!

### ISSUE THREAD

**Issue by azsh07** [benoit74/nzy3d-api#1]
This nzy3d-api is very good since no many developer want to develop surface chart 3d in open source. 

i tried your wpfdemo and it work. However, i can't make it work in winforms. Can you provide documentation how to implement this chart into winforms project.

Thank you and have a nice day

**Comment by benoit74** [comment]
I've added a Winforms demo to the github repo and it works well. There is only a very small glitch is the demo in the sense that you have to stop the graph from rotating in order to display checkboxes. I have no clue why and no time to investigate (just don't start the camera movement on form load and it will be ok)
But anyway, the control work very well in Winforms. You can use it by directly adding a Renderer3d on the form from the toolbox (should be displayed in a section named 'nzy3d-api' of the toolbox - if not, search the web to learn how to add controls in the toolbox from referenced librairires).
